apiVersion: apps/v1
kind: Job
metadata:
  name: webserver
  namespace: zadatak_2
spec:
  replicas: 1
  selector:
    matchLabels:
      zadatak: dva
  template:
    metadata:
      labels:
        zadatak: 
    spec:
      containers:
      - name: sara_konstantinovic_4118s
        image: webserver:1.0
